

spring.application.name=DOSW-Library

spring.datasource.url=jdbc:postgresql://localhost:5432/dosw_library
spring.datasource.username=postgres
spring.datasource.password=Lauravale0201
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:80}

# MongoDB Atlas
spring.data.mongodb.uri=mongodb://doswAdmin:LauraVale0201@ac-bqhm80g-shard-00-00.ogwu32i.mongodb.net:27017,ac-bqhm80g-shard-00-01.ogwu32i.mongodb.net:27017,ac-bqhm80g-shard-00-02.ogwu32i.mongodb.net:27017/?ssl=true&replicaSet=atlas-o8ia3d-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.database=dosw_library
spring.profiles.active=mongo